<Project Sdk="Microsoft.NET.Sdk">


	<ItemGroup>
		<ProjectReference Include="..\MiniProject.Modules.Events.Application\MiniProject.Modules.Events.Application.csproj" />
		<ProjectReference Include="..\MiniProject.Modules.Events.Presentation\MiniProject.Modules.Events.Presentation.csproj" />
	</ItemGroup>

</Project>
