version: '3.9'

services:
  miniproject.api:
    environment:
      - ASPNETCORE_HTTP_PORTS=5022
      - ASPNETCORE_HTTPS_PORTS=5021
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
   
  miniproject.api2:
    environment:
      - ASPNETCORE_HTTPS_PORTS=5025
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro