version: '3.9'

services:
  miniproject.api:
    image: ${DOCKER_REGISTRY-}miniprojectapi
    container_name: MiniProject-BE.Api
    build:
      context: src
      dockerfile: API/MiniProject.Api/MiniProject.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    depends_on:
      - miniproject.rabbitmq   
    environment:
      RabbitMQ__Host: miniproject.rabbitmq      
      RabbitMQ__Username: guest  
      RabbitMQ__Password: guest

  miniproject.database:
    image: postgres:latest
    container_name: MiniProject.Database
    environment:
      - POSTGRES_DB=evently
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5433:5433

  miniproject.rabbitmq:
    image: rabbitmq:3-management            
    container_name: MiniProject.RabbitMQ    
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest     
      RABBITMQ_DEFAULT_PASS: guest         
