version: '3.9'

services:
  miniproject.api:
    image: ${DOCKER_REGISTRY-}miniprojectapi
    container_name: MiniProject-BE.Api
    build:
      context: src/API/MiniProject.Api/MiniProject.Api
      dockerfile: Dockerfile
    ports:
      - 5021:5021
      - 5022:5022
      - 5023:5023
    depends_on:
      - miniproject.rabbitmq   
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5022;http://+:5023;https://+:5021
      RabbitMQ__Host: miniproject.rabbitmq      
      RabbitMQ__Username: guest  
      RabbitMQ__Password: guest

  miniproject.api2:
    image: ${DOCKER_REGISTRY-}miniprojectapi
    container_name: MiniProject-BE-2.Api
    build:
      context: src/API/MiniProject.Api2
      dockerfile: Dockerfile
    ports:
      - 5025:5025
    depends_on:
      - miniproject.rabbitmq   
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:5025
      RabbitMQ__Host: miniproject.rabbitmq      
      RabbitMQ__Username: guest  
      RabbitMQ__Password: guest

  miniproject.database:
    image: postgres:latest
    container_name: MiniProject.Database
    environment:
      - POSTGRES_DB=evently
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5433:5433

  miniproject.rabbitmq:
    image: rabbitmq:3-management            
    container_name: MiniProject.RabbitMQ    
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest     
      RABBITMQ_DEFAULT_PASS: guest         
