<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiniProject.Modules.Authentification.Domain\MiniProject.Modules.Authentification.Domain.csproj" />
  </ItemGroup>

</Project>
