//<auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MiniProject.Modules.Ticketing.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class CustomerTableChange : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "first_name",
                schema: "ticketing2",
                table: "customers");

            migrationBuilder.RenameColumn(
                name: "last_name",
                schema: "ticketing2",
                table: "customers",
                newName: "name");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "name",
                schema: "ticketing2",
                table: "customers",
                newName: "last_name");

            migrationBuilder.AddColumn<string>(
                name: "first_name",
                schema: "ticketing2",
                table: "customers",
                type: "text",
                nullable: false,
                defaultValue: "");
        }
    }
}
