<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="EFCore.NamingConventions" Version="9.0.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
		<PackageReference Include="MediatR" Version="12.4.1" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\MiniProject.Modules.Users.Application\MiniProject.Modules.Users.Application.csproj" />
		<ProjectReference Include="..\MiniProject.Modules.Users.Presentation\MiniProject.Modules.Users.Presentation.csproj" />
		<ProjectReference Include="..\MiniProject.Modules.Users.PublicAPI\MiniProject.Modules.Users.PublicAPI.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Database\Migrations\" />
	</ItemGroup>

</Project>
