<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="EFCore.NamingConventions" Version="9.0.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
		<PackageReference Include="MassTransit" Version="8.4.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
		<PackageReference Include="MediatR" Version="12.4.1" />
		<PackageReference Include="Quartz.Extensions.Hosting" Version="3.14.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\Common\MiniProject.Common.Messaging.Contracts\MiniProject.Common.Messaging.Contracts.csproj" />
		<ProjectReference Include="..\MiniProject.Modules.Users.Application\MiniProject.Modules.Users.Application.csproj" />
		<ProjectReference Include="..\MiniProject.Modules.Users.Presentation\MiniProject.Modules.Users.Presentation.csproj" />
		<ProjectReference Include="..\MiniProject.Modules.Users.PublicApi\MiniProject.Modules.Users.PublicApi.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Database\Migrations\" />
	</ItemGroup>

</Project>
