<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="12.4.1" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MiniProject.Modules.Events.Domain\MiniProject.Modules.Events.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Abstraction\" />
	</ItemGroup>

</Project>
