<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
	  <PackageReference Include="MediatR" Version="12.4.1" />
	  <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.0" />
	  <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Common\MiniProject.Common.Messaging.Contracts\MiniProject.Common.Messaging.Contracts.csproj" />
		<ProjectReference Include="..\..\Users\MiniProject.Modules.Users.PublicApi\MiniProject.Modules.Users.PublicApi.csproj" />
		<ProjectReference Include="..\MiniProject.Modules.Events.Application\MiniProject.Modules.Events.Application.csproj" />
		<ProjectReference Include="..\MiniProject.Modules.Events.Domain\MiniProject.Modules.Events.Domain.csproj" />
	</ItemGroup>

</Project>
